/**
 * Copyright IBM Corp. 2015, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

const { reporter } = require('@carbon/cli-reporter');
const fs = require('fs-extra');
const path = require('path');
const prettier = require('prettier');
const { formatTokenName, themes, tokens } = require('../lib');

const FILE_BANNER = `// Code generated by @carbon/themes. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2018
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//
`;
const SCSS_DIR = path.resolve(__dirname, '../scss');
const MIXINS_ENTRYPOINT = path.join(SCSS_DIR, '_mixins.scss');
const VARIABLES_ENTRYPOINT = path.join(SCSS_DIR, '_variables.scss');

const defaultTheme = 'white';
const defaultThemeMapName = `$carbon--theme`;
const prettierOptions = {
  parser: 'scss',
  printWidth: 80,
  singleQuote: true,
  trailingComma: 'es5',
};

async function build() {
  reporter.info('Building scss files for themes...');

  // Create maps for each theme:
  // $carbon--theme--name: (
  //   token-name: token-value
  // ) !default !global;
  const themeMaps = Object.keys(themes)
    .map(name => {
      const theme = themes[name];
      let scssMap = `$carbon--theme--${name}: (`;
      scssMap += '\n';

      for (const key of Object.keys(theme)) {
        const name = formatTokenName(key);
        const value = theme[key];
        scssMap += `  ${name}: ${value},`;
        scssMap += '\n';
      }

      scssMap += ') !default !global;';
      scssMap += '\n';

      return scssMap;
    })
    .join('\n');

  // Create carbon--theme mixin, takes a theme as input and assigns all theme
  // variables conditionally using `!default` and `!global` flags before
  // resetting at the end of the function block
  let themeMixin = `/// Define theme variables
/// @access public
/// @param {Map} $theme - map of theme tokens
/// @param {Bool} $default - if !default flag should be included
@mixin carbon--theme($theme: ${defaultThemeMapName}, $default: true) {\n`;

  themeMixin += `  @if $default {\n`;

  // Initialize variables in mixin with !default flag
  for (const tokenGroup of Object.keys(tokens)) {
    for (const token of tokens[tokenGroup]) {
      const name = formatTokenName(token);
      themeMixin += `    $${name}: map-get($theme, ${name}) !default !global;\n`;
    }
  }

  themeMixin += `  } @else {\n`;

  // Initialize variables in mixin without !default flag
  for (const tokenGroup of Object.keys(tokens)) {
    for (const token of tokens[tokenGroup]) {
      const name = formatTokenName(token);
      themeMixin += `    $${name}: map-get($theme, ${name}) !global;\n`;
    }
  }

  themeMixin += `  }\n`;

  // Content block
  themeMixin += '\n';
  themeMixin += '  @content;';
  themeMixin += '\n';

  // If block for default theme to reset mixin
  themeMixin += '\n';
  themeMixin += `  // Reset to default theme after apply in content`;
  themeMixin += '\n';
  themeMixin += `  @if $theme != ${defaultThemeMapName} {
    @include carbon--theme(${defaultThemeMapName}, $default);
  }`;
  themeMixin += '\n';
  themeMixin += '}';

  // Files
  const variables = `${FILE_BANNER}

${themeMaps}

${defaultThemeMapName}: $carbon--theme--${defaultTheme} !default !global`;

  const mixins = `${FILE_BANNER}
@import './variables';

${themeMixin}`;

  await fs.ensureDir(SCSS_DIR);
  await fs.writeFile(
    VARIABLES_ENTRYPOINT,
    prettier.format(variables, prettierOptions)
  );
  await fs.writeFile(
    MIXINS_ENTRYPOINT,
    prettier.format(mixins, prettierOptions)
  );

  reporter.info('Done! ✨');
}

build().catch(error => {
  console.error(error);
});
